### ISSUE TITLE
У меня нет папки BCC55

### ISSUE THREAD

**Issue by DinkiGonki** [LencoDigitexer/VSCode_borland_setup#2]

**Comment by LencoDigitexer** [comment]
ОРнул

**Comment by LencoDigitexer** [comment]
Вот дерево каталога
C:.
├───BCC55
│   ├───Bin
│   ├───Examples
│   │   └───StdLib
│   ├───Help
│   ├───Include
│   │   ├───Gl
│   │   ├───Rw
│   │   └───Sys
│   └───Lib
│       └───PSDK
├───BORLANDC
│   ├───BGI
│   ├───BIN
│   ├───CLASSLIB
│   │   ├───EXAMPLES
│   │   ├───INCLUDE
│   │   ├───LIB
│   │   └───SOURCE
│   ├───CRTL
│   │   ├───CLIB
│   │   ├───EMU
│   │   ├───IOSTREAM
│   │   ├───MATH
│   │   ├───RTLINC
│   │   └───WINLIB
│   │       └───INDEP
│   ├───DOC
│   ├───EXAMPLES
│   │   ├───TASM
│   │   │   ├───FILT
│   │   │   ├───HEAP
│   │   │   ├───QUEUE
│   │   │   └───WHEREIS
│   │   ├───TCALC
│   │   ├───TD
│   │   ├───TPROF
│   │   ├───WIN30
│   │   ├───WIN31
│   │   │   ├───CHELP
│   │   │   ├───CLIOLE
│   │   │   ├───CMDLG
│   │   │   ├───DDEML
│   │   │   ├───DRAGDROP
│   │   │   ├───SOUNDER
│   │   │   └───TRUETYPE
│   │   └───WORKSHOP
│   ├───INCLUDE
│   │   └───SYS
│   ├───LIB
│   │   └───STARTUP
│   ├───OWL
│   │   ├───DOC
│   │   ├───EXAMPL31
│   │   │   ├───ACLOCK
│   │   │   ├───CMDLGAP
│   │   │   ├───DDEML
│   │   │   ├───DRAGDROP
│   │   │   ├───OLECLNT
│   │   │   ├───OLESRVR
│   │   │   ├───OWLHELP
│   │   │   ├───OWLPEN
│   │   │   ├───SCRNSAVE
│   │   │   ├───SHELLAPI
│   │   │   ├───SOUNDPLY
│   │   │   └───TTFONT
│   │   ├───EXAMPLES
│   │   │   ├───CALC
│   │   │   ├───CHECKERS
│   │   │   ├───CHESS
│   │   │   ├───CURSOR
│   │   │   ├───FILEAPP
│   │   │   ├───GDIDEMO
│   │   │   ├───MFILEAPP
│   │   │   ├───OWLPRINT
│   │   │   ├───PAINT
│   │   │   ├───PROGTALK
│   │   │   ├───STEPS
│   │   │   ├───SWAT
│   │   │   ├───SYSINFO
│   │   │   └───TTT
│   │   ├───INCLUDE
│   │   ├───LIB
│   │   ├───OBJECT
│   │   │   ├───DL
│   │   │   ├───WL
│   │   │   ├───WM
│   │   │   └───WS
│   │   └───SOURCE
│   ├───REDIST
│   └───TVISION
│       ├───DEMOS
│       ├───DOCDEMOS
│       ├───HELP
│       ├───INCLUDE
│       ├───LIB
│       └───SOURCE
├───CHR
├───DOSBox
│   └───zmbv
├───fil_dat
├───h
├───KeyRus
└───Program

**Comment by LencoDigitexer** [comment]
Скачай https://github.com/LencoDigitexer/VSCode_borland_setup/releases/download/borland/Borland.zip заново.
Удали Старую папку borland с диска C и скопируй распакованный архив

**Comment by DinkiGonki** [comment]
Ой пасиба так неожиданно и пириятноо, очень пириятно <3
